version: '2'
services:
    gestdepsys-app:
        image: gestdepsys
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestdepsys-mysql:3306/gestdepsys?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gestdepsys-elasticsearch:9300
        ports:
            - 8190:8190
    gestdepsys-mysql:
        extends:
            file: mysql.yml
            service: gestdepsys-mysql
    gestdepsys-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gestdepsys-elasticsearch
